# Generated by Django 4.2.21 on 2025-06-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stories/"),
        ),
    ]
