# Generated by Django 5.2.2 on 2025-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0006_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="stories.userprofile"
            ),
        ),
    ]
