# Generated by Django 5.2.2 on 2025-06-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0007_userprofile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="about",
            field=models.TextField(blank=True, verbose_name="About Me"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
